# This workflow will deploy the sandbox as static content to GitHub Pages.

name: â˜„ï¸ Deploy Sandbox

on:
  workflow_dispatch:
    inputs:
      basePath:
        description: |
          The base path to deploy the sandbox to. Default is "identity-integration-ui-templates" (https://wso2-extensions.github.io/identity-integration-ui-templates).
          Note: Do not include a leading or trailing slash.
        default: "identity-integration-ui-templates"
        type: string

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]
        pnpm-version: [8.7.4]
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ env.GH_TOKEN }}

      - name: ğŸŸ¢ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ¥¡ Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false

      - name: ğŸˆ Get pnpm store directory
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_ENV

      - name: ğŸ§© Install Dependencies
        run: |
          cd tools/sandbox
          pnpm bootstrap

      - name: ğŸ—ï¸ Build Project
        run: |
          cd tools/sandbox
          export BASE_PATH="/${{ github.event.inputs.basePath }}"
          pnpm build

      - name: âš™ï¸ Setup Pages
        uses: actions/configure-pages@v3

      - name: ğŸŒ© Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./tools/sandbox/apps/markdown-editor/dist

      - name: ğŸ”¥ Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
